# This is the staging variant of
# docker deployment for {{app_name}}
version: '3'
services:

  # staging instance
  app-staging:
    image: index.docker.io/{{docker_account}}/{{app_name}}:staging
    container_name: 'app-staging'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=staging
      - MONGO_HOST=database
      - MONGO_DB={{app_name}}-staging
      - HOST=http://{{aws_staging}}/staging/api/
      - RABBITMQ_HOST={{rabbitmq_staging_host}}
      - RABBITMQ_USER={{rabbitmq_staging_user}}
      - RABBITMQ_PASSWORD={{rabbitmq_staging_password}}
      - RABBITMQ_HEARTBEAT=259200
    env_file:
      - .env

  app-admin:
    image: index.docker.io/{{docker_account}}/{{app_name}}:staging
    container_name: 'app-admin'
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=staging
      - URL=http://{{aws_staging}}/staging/api/


  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app-staging
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx-staging.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs

  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup
