name: Docker Image CI

on:
  push:
    branches: [ development ]
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: build
      run: |
        echo "Authenticating docker"
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_AUTH_TOKEN }}
        echo "Building docker image"
        docker build -t shoal/ui:${GITHUB_REF##*/} --build-arg MACHINE_NAME=ui:${GITHUB_REF##*/} .
        echo "Build the image"
        docker push shoal/ui:${GITHUB_REF##*/}
        echo "Pushed the shoal/ui:${GITHUB_REF##*/} to the Docker"
