name: Docker Image CI
on:
  push:
    branches: [ development ]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]
    steps:
    - uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        status: STARTED
        color: good
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: build
      run: |
        echo "Authenticating docker"
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_AUTH_TOKEN }}
        echo "Building docker image"
        docker build -t {{app_name}}/ui:${GITHUB_REF##*/} --build-arg MACHINE_NAME=ui:${GITHUB_REF##*/} .
        echo "Build the image"
        docker push {{app_name}}/ui:${GITHUB_REF##*/}
        echo "Pushed the {{app_name}}/ui:${GITHUB_REF##*/} to the Docker"
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        status: SUCCESS
        color: good
    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        status: FAILED
        color: danger
